[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.13"

# Optional: Add remappings
remappings = [
    "forge-std/=lib/forge-std/src/"
]

# Optional: Gas reporting
gas_reports = ["Storage"]

# Optional: Verbose output
verbosity = 2