// abi.js
export const contractABI = [
  {
    type: "function",
    name: "addExpense",
    inputs: [
      { name: "expname", type: "string", internalType: "string" },
      { name: "paidby", type: "string", internalType: "string" },
      { name: "person1", type: "string", internalType: "string" },
      { name: "person2", type: "string", internalType: "string" },
      { name: "paddress", type: "string", internalType: "string" },
      { name: "amt", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expenses",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "expname", type: "string", internalType: "string" },
      { name: "paidby", type: "string", internalType: "string" },
      { name: "person1", type: "string", internalType: "string" },
      { name: "person2", type: "string", internalType: "string" },
      { name: "paddress", type: "string", internalType: "string" },
      { name: "amt", type: "uint256", internalType: "uint256" },
      { name: "shareamount", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getExpense",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct ExpenseSharing.Expense",
        components: [
          { name: "expname", type: "string", internalType: "string" },
          { name: "paidby", type: "string", internalType: "string" },
          { name: "person1", type: "string", internalType: "string" },
          { name: "person2", type: "string", internalType: "string" },
          { name: "paddress", type: "string", internalType: "string" },
          { name: "amt", type: "uint256", internalType: "uint256" },
          { name: "shareamount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resetexp",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateexpense",
    inputs: [
      { name: "expname", type: "string", internalType: "string" },
      { name: "paidby", type: "string", internalType: "string" },
      { name: "person1", type: "string", internalType: "string" },
      { name: "person2", type: "string", internalType: "string" },
      { name: "paddress", type: "string", internalType: "string" },
      { name: "amt", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
];
